@rootAPI = http://localhost:8000/api/v1/users

### create new admin
POST {{rootAPI}}/admin
Content-Type: application/json

{
  "fname":"Ranjit",
  "lname":"Acharya",
  "phone":"0123456789",
  "email":"r@r.com",
  "password":"1"
}

###login user
POST {{rootAPI}}/login
Content-Type: application/json

{
  "email":"r@r.com",
  "password":"1"
}

###get user after login
GET {{rootAPI}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJAci5jb20iLCJpYXQiOjE3MDQ5NzkxMzUsImV4cCI6MTcwNDk4MDAzNX0.9Kulu_AtpSmROZesDHxZZw-hU8RnSNRC97MoteqNtv8


